using Microsoft.CodeAnalysis;

namespace Generators;

[Generator]
public sealed class HelloWorldGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext ctx)
    {
        ctx.RegisterSourceOutput(ctx.CompilationProvider, static (spc, _) =>
        {
            spc.AddSource("Hello.g.cs",
                """
                // <auto-generated/>
                public static class Hello
                {
                    public static string Message => "Hello from an incremental generator!";
                }
                """);
        });
    }
}
