using Annotations;
using App;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

Console.WriteLine(Hello.Message); // Stage 0: generated

// --------------------------------

var services = new ServiceCollection()
	.AddGeneratedServices(); // generated by the Stage 2 generator

using var sp = services.BuildServiceProvider();
Console.WriteLine(sp.GetRequiredService<IOrderService>().Ping());
Console.WriteLine(sp.GetRequiredService<ITimeProvider>().UtcNow);
Console.WriteLine(sp.GetRequiredService<OrderService>().Ping()); // AsSelf = true


public interface IOrderService { string Ping(); }

[Service(Lifetime.Singleton, AsSelf = true)]
public class OrderService : IOrderService
{
	public string Ping() => "pong";
}

[Service(As = typeof(ITimeProvider), Lifetime = Lifetime.Transient)]
public class Clock : ITimeProvider
{
	public DateTime UtcNow => DateTime.UtcNow;
}
public interface ITimeProvider { DateTime UtcNow { get; } }