//HintName: OrderId.StrongId.g.cs
// <auto-generated/>
#nullable enable
public readonly partial struct OrderId : System.IEquatable<OrderId>
{
    private readonly System.Guid _value;
    public OrderId(System.Guid value) => _value = value;

    public static implicit operator System.Guid(OrderId id) => id._value;
    public static explicit operator OrderId(System.Guid value) => new(value);

    public bool Equals(OrderId other) => System.Collections.Generic.EqualityComparer<System.Guid>.Default.Equals(_value, other._value);
    public override bool Equals(object? obj) => obj is OrderId other && Equals(other);
    public override int GetHashCode() => System.Collections.Generic.EqualityComparer<System.Guid>.Default.GetHashCode(_value);
    public override string ToString() => _value.ToString();
            
    public static OrderId New() => new(System.Guid.NewGuid());

    public static bool TryParse(string? s, out OrderId value)
    {
        var ok = System.Guid.TryParse(s, out var g);
        value = ok ? new(g) : default;
        return ok;
    }
}
